import{S as E,i as n,a as h}from"./assets/vendor-DtICNKEH.js";(function(){const a=document.createElement("link").relList;if(a&&a.supports&&a.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function r(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=r(e);fetch(e.href,s)}})();const m=document.querySelector(".form-search"),w=document.querySelector(".form-input"),p=document.querySelector(".gallery"),c=document.getElementById("loader"),t=document.getElementById("load-more"),g="56498857-093082d3f79dc0abc424cf2fd",f="https://pixabay.com/api/";let l=1,y="";const u=20;let S=new E(".gallery a",{captionsData:"alt",captionDelay:250});m.addEventListener("submit",async o=>{o.preventDefault();const a=w.value.trim();if(l=1,y=a,t.classList.add("hidden"),t.classList.remove("is-active"),!a){n.warning({title:"Warning",message:"Please enter a search query!",position:"topRight"});return}p.innerHTML="",c.classList.remove("is-hidden");const r={params:{key:g,q:a,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:u,page:l}};try{const e=(await h.get(f,r)).data;if(c.classList.add("is-hidden"),m.reset(),e.hits.length===0){t.classList.add("hidden"),t.classList.remove("is-active"),n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}L(e.hits,!0),e.totalHits<=l*u&&(t.classList.add("hidden"),t.classList.remove("is-active"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(i){c.classList.add("is-hidden"),t.classList.add("hidden"),t.classList.remove("is-active"),m.reset(),n.error({title:"Error",message:`Bir sistem hatası oluştu: ${i.message}`,position:"topRight"})}});t.addEventListener("click",async()=>{l+=1,c.classList.remove("is-hidden"),t.classList.add("hidden");const o={params:{key:g,q:y,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:u,page:l}};try{const r=(await h.get(f,o)).data;c.classList.add("is-hidden"),L(r.hits,!1),r.totalHits<=l*u&&(t.classList.add("hidden"),t.classList.remove("is-active"),n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(a){c.classList.add("is-hidden"),n.error({title:"Error",message:a.message,position:"topRight"})}});function L(o,a){const r=o.map(({webformatURL:i,largeImageURL:e,tags:s,likes:d,views:v,comments:b,downloads:q})=>`
      <li class="card">
        <a class="card-link" href="${e}">
          <img class="card-image" src="${i}" alt="${s}" title="${s}"/>
        </a>
        <ul class="card-stats">
          <li class="stat-item"><span class="stat-label">Likes</span><span class="stat-value">${d}</span></li>
          <li class="stat-item"><span class="stat-label">Views</span><span class="stat-value">${v}</span></li>
          <li class="stat-item"><span class="stat-label">Comments</span><span class="stat-value">${b}</span></li>
          <li class="stat-item"><span class="stat-label">Downloads</span><span class="stat-value">${q}</span></li>
        </ul>
      </li>
    `).join("");if(a)p.innerHTML=r;else{p.insertAdjacentHTML("beforeend",r);const i=p.querySelector(".card");if(i){const e=i.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}S.refresh(),t.classList.remove("hidden"),t.classList.add("is-active")}
//# sourceMappingURL=index.js.map
